/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as DataIntegrityRouteImport } from './routes/data-integrity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRbzScrapeRouteImport } from './routes/api/public/rbz.scrape'
import { Route as ApiPublicRbzPdfRouteImport } from './routes/api/public/rbz.pdf'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntegrityRoute = DataIntegrityRouteImport.update({
  id: '/data-integrity',
  path: '/data-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRbzScrapeRoute = ApiPublicRbzScrapeRouteImport.update({
  id: '/api/public/rbz/scrape',
  path: '/api/public/rbz/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRbzPdfRoute = ApiPublicRbzPdfRouteImport.update({
  id: '/api/public/rbz/pdf',
  path: '/api/public/rbz/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
  '/api/public/rbz/pdf': typeof ApiPublicRbzPdfRoute
  '/api/public/rbz/scrape': typeof ApiPublicRbzScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
  '/api/public/rbz/pdf': typeof ApiPublicRbzPdfRoute
  '/api/public/rbz/scrape': typeof ApiPublicRbzScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
  '/api/public/rbz/pdf': typeof ApiPublicRbzPdfRoute
  '/api/public/rbz/scrape': typeof ApiPublicRbzScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/data-integrity'
    | '/workbench'
    | '/api/public/rbz/pdf'
    | '/api/public/rbz/scrape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/data-integrity'
    | '/workbench'
    | '/api/public/rbz/pdf'
    | '/api/public/rbz/scrape'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/data-integrity'
    | '/workbench'
    | '/api/public/rbz/pdf'
    | '/api/public/rbz/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DataIntegrityRoute: typeof DataIntegrityRoute
  WorkbenchRoute: typeof WorkbenchRoute
  ApiPublicRbzPdfRoute: typeof ApiPublicRbzPdfRoute
  ApiPublicRbzScrapeRoute: typeof ApiPublicRbzScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-integrity': {
      id: '/data-integrity'
      path: '/data-integrity'
      fullPath: '/data-integrity'
      preLoaderRoute: typeof DataIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rbz/scrape': {
      id: '/api/public/rbz/scrape'
      path: '/api/public/rbz/scrape'
      fullPath: '/api/public/rbz/scrape'
      preLoaderRoute: typeof ApiPublicRbzScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rbz/pdf': {
      id: '/api/public/rbz/pdf'
      path: '/api/public/rbz/pdf'
      fullPath: '/api/public/rbz/pdf'
      preLoaderRoute: typeof ApiPublicRbzPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DataIntegrityRoute: DataIntegrityRoute,
  WorkbenchRoute: WorkbenchRoute,
  ApiPublicRbzPdfRoute: ApiPublicRbzPdfRoute,
  ApiPublicRbzScrapeRoute: ApiPublicRbzScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
