/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as DataIntegrityRouteImport } from './routes/data-integrity'
import { Route as IndexRouteImport } from './routes/index'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntegrityRoute = DataIntegrityRouteImport.update({
  id: '/data-integrity',
  path: '/data-integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-integrity': typeof DataIntegrityRoute
  '/workbench': typeof WorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/data-integrity' | '/workbench'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data-integrity' | '/workbench'
  id: '__root__' | '/' | '/data-integrity' | '/workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataIntegrityRoute: typeof DataIntegrityRoute
  WorkbenchRoute: typeof WorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-integrity': {
      id: '/data-integrity'
      path: '/data-integrity'
      fullPath: '/data-integrity'
      preLoaderRoute: typeof DataIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataIntegrityRoute: DataIntegrityRoute,
  WorkbenchRoute: WorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
